# Generated by Django 4.1.1 on 2022-11-26 22:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('poster_url', models.URLField(null=True)),
            ],
        ),
    ]
