# Generated by Django 3.2.16 on 2022-11-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='data_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
