# Generated by Django 4.1.3 on 2022-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0004_propostas_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propostas',
            name='is_active',
        ),
    ]
