# Generated by Django 4.1.3 on 2022-12-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_empresa_email_remove_estudante_email_and_more'),
        ('propostas', '0005_remove_propostas_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='empresa',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='user.empresa'),
            preserve_default=False,
        ),
    ]
