# Generated by Django 4.1.3 on 2022-12-03 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propostas', '0006_propostas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostas',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
