# Generated by Django 4.1.3 on 2022-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_curriculo_id_alter_curriculo_estudante'),
        ('propostas', '0007_alter_propostas_data_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostas',
            name='inscrito',
            field=models.ManyToManyField(blank=True, default=None, to='curriculo.curriculo'),
        ),
    ]
