# Generated by Django 4.1.3 on 2022-11-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_empresa_email_remove_estudante_email_and_more'),
        ('curriculo', '0003_alter_curriculo_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=22, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='estudante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.estudante'),
        ),
    ]
