# Generated by Django 4.1.3 on 2022-12-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_curriculo_id_alter_curriculo_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculo.curso'),
        ),
    ]
